# Generated by Django 4.2.7 on 2023-11-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(max_length=255)),
                ('article_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='vtanz/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
