# Generated by Django 4.2.7 on 2023-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtanz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archiv'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(max_length=255, verbose_name='Artikel Kürzel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=255, verbose_name='Überschrift'),
        ),
    ]
