# Generated by Django 4.2.6 on 2023-10-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r3cord', '0002_alter_record_image_alter_record_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
